config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :calories, :carbohydrates, :proteins, :fats, presence: true

 def day
   self.created_at.strftime("%B %e, %Y")
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all.where("created_at >= ?", Time.zone.now.beginning_of_day).order("created_at ASC")
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<%= content_for :title do%>
    FoodLog Archives
<% end %>

<div id="entries" class="w-full flex flex-col items-center justify-center">
  <% @entries.each do |day, entries| %>
    <h2 class="text-2xl font-bold mb-2"><%= day %></h2>
    
    <div>
        <div class="stats stats-vertical lg:stats-horizontal shadow mb-6">
        
        <div class="stat">
            <div class="stat-title">Calories</div>
            <div class="stat-value">
                <%= entries.pluck(:calories).sum %>
            </div>
        </div>
        
        <div class="stat">
            <div class="stat-title">Carbohydrates</div>
            <div class="stat-value">
                <%= entries.pluck(:carbohydrates).sum %>
            </div>
        </div>
        
        <div class="stat">
            <div class="stat-title">Proteins</div>
            <div class="stat-value">
                <%= entries.pluck(:proteins).sum %>
            </div>
        </div>

        <div class="stat">
            <div class="stat-title">Fats</div>
            <div class="stat-value">
                <%= entries.pluck(:fats).sum %>
            </div>
        </div>
        
        </div>
    </div>

    <% entries.each do |entry| %>
        <div class=" w-full flex flex-col justify-center">
            <%= link_to entry_path(entry) do %>
                <div class="card w-2/3 mx-auto rounded-xl px-8 py-4 mb-4 bg-gray-900 shadow-xl">
                    <div class="flex items-start justify-between mb-2">
                        <h3 class="self-start text-xl font-bold"><%= entry.meal_type %></h3>
                        <p class="font-semibold"><%= entry.created_at.strftime("%B %e %Y") %></p>
                    </div>
                    <hr class="border-t-2 border-gray-500">
                    <div class="flex flex-col md:flex-row items-center justify-between">
                        <strong class="text-lg font-bold flex flex-col items-center">
                            Calories
                            <span class="text-sm text-center font-normal">
                                <%= entry.calories %>
                            </span>
                        </strong>
                        <strong class="text-lg font-bold flex flex-col items-center">
                            Carbohydrates
                            <span class="text-sm font-normal">
                                <%= entry.carbohydrates %>
                            </span>
                        </strong>

                        <strong class="text-lg font-bold flex flex-col items-center">
                            Proteins
                            <span class="text-sm font-normal">
                                <%= entry.proteins %>
                            </span>
                        </strong>
                        <strong class="text-lg font-bold flex flex-col items-center">
                            Fats
                            <span class="text-sm font-normal">
                                <%= entry.fats %>
                            </span>
                        </strong>
                    </div>
                </div>
            <% end %>
        </div>
    <% end %>
  <% end %>
  </div>
</div>

<div class="w-full flex justify-center mt-4">
  <%= link_to "Entries", root_path, class: "btn btn-ghost" %>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" class="card rounded-lg bg-base-100 shadow-x mb-4">
  <dl class="-my-3 divide-y divide-gray-100 text-sm dark:divide-gray-700">

    <div
      class="flex items-center justify-center p-3 bg-gray-50 sm:gap-4 dark:bg-gray-900"
    >
      <dd class="text-gray-500 font-bold text-xl sm:col-span-2 dark:text-gray-100">  <%= entry.meal_type %> </dd>
    </div>

    <div
      class="flex items-center justify-between p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800"
    >
      <dt class="font-medium text-gray-900 dark:text-white">Calories</dt>
      <dd class="text-gray-700 sm:col-span-2 dark:text-gray-200">
        <%= entry.calories %>
      </dd>
    </div>

    <div
      class="flex items-center justify-between p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800"
    >
      <dt class="font-medium text-gray-900 dark:text-white">
        Proteins
      </dt>
      <dd class="text-gray-700 sm:col-span-2 dark:text-gray-200">
        <%= entry.proteins %>
      </dd>
    </div>

    <div
      class="flex items-center justify-between p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800"
    >
      <dt class="font-medium text-gray-900 dark:text-white">
        Carbohydrates
      </dt>
      <dd class="text-gray-700 sm:col-span-2 dark:text-gray-200">
        <%= entry.carbohydrates %>
      </dd>
    </div>

    <div
      class="flex items-center justify-between p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800"
    >
      <dt class="font-medium text-gray-900 dark:text-white">Fats</dt>
      <dd class="text-gray-700 sm:col-span-2 dark:text-gray-200">
        <%= entry.fats %>
      </dd>
    </div>

    <div
      class="flex items-center justify-between p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800"
    >
      <dt class="font-medium text-gray-900 dark:text-white">Logged</dt>
      <dd class="text-gray-700 sm:col-span-2 dark:text-gray-200">
        <%= time_ago_in_words(entry.created_at) %>
      </dd>
    </div>

    <div
      class="flex p-3 bg-gray-50 sm:gap-4 dark:bg-gray-800 justify-center"
    >
      <div class="join rounded-none">
    
          <%= link_to "Show", entry, class: "btn join-item hover:text-primary" %>
        
          <%= link_to "Edit", edit_entry_path(entry), class: "btn join-item hover:text-secondary" %>
        
        
          <%= button_to "Delete", entry, method: :delete, data: { confirm: "Are you sure?" }, class: "btn join-item hover:text-error" %>
      
      </div>
    </div>

  </dl>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>

  <% if entry.errors.any? %>
    <div role="alert" class="alert alert-error rounded-b-none">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:
        </p>
    </div>
    <ul class="alert alert-error rounded-t-none flex flex-col items-start gap-2">
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :meal_type, class: "input input-bordered flex items-center gap-2 mb-4 w-96 mt-4" do %>
    Meal Type
    <%= form.text_field :meal_type, class: "grow" %>
    <% end %>
  </div>

  <div>
    <%= form.label :calories, class: "input input-bordered flex items-center gap-2 mb-4 w-96" do %>
    Calories
    <%= form.number_field :calories, class: "grow" %>
    <% end %>
  </div>

  <div>
    <%= form.label :proteins, class: "input input-bordered flex items-center gap-2 mb-4 w-96" do %>
    Proteins
    <%= form.number_field :proteins, class: "grow" %>
    <% end %>
  </div>

  <div>
    <%= form.label :carbohydrates, class: "input input-bordered flex items-center gap-2 mb-4 w-96" do %>
    Carbohydrates
    <%= form.number_field :carbohydrates, class: "grow" %>
    <% end %>
  </div>

  <div>
    <%= form.label :fats, class: "input input-bordered flex items-center gap-2 mb-4 w-96" do %>
    Fats
    <%= form.number_field :fats, class: "grow" %>
    <% end %>
  </div>

  <div class="w-full flex justify-center">
    <%= form.submit class: "btn btn-primary w-full" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="w-full flex justify-center mb-4">
  <div class="card min-w-min bg-base-100 p-4 shadow-xl">

    <h1 class="text-xl text-center mb-4" >Edit Entry</h1>

      <%= render "form", entry: @entry %>

      <br>

  </div>
</div>

<div class="w-full flex justify-center">
  <div class="join">
    <%= link_to "Show this entry", @entry, class: "join-item btn" %> 
    <%= link_to "Back to entries", entries_path, class: "join-item btn" %>
  </div>
</div>

app/views/entries/index.html.erb
<%= content_for :title do %>
  FoodLog - <%= DateTime.now.strftime('%B %e %Y') %>
<% end %>

<div id="entries">
  <div class="grid grid-cols-3 gap-4">
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
  </div>
</div>

<div class="w-full flex justify-center mt-4">
  <%= link_to "Archives", archives_index_path, class: "btn btn-ghost" %>
</div>

app/views/entries/new.html.erb
<div class="w-full flex justify-center mb-4">
  <div class="card min-w-min bg-base-100 p-4 shadow-xl">

    <h1 class="text-xl text-center mb-4" >New entry</h1>

    <%= render "form", entry: @entry %>

    <br>

  </div>
</div>

<div class="w-full flex justify-center">
  <div class="join">
    <%= link_to "Show this entry", @entry, class: "join-item btn" %> 
    <%= link_to "Back to entries", entries_path, class: "join-item btn" %>
  </div>
</div>

app/views/entries/show.html.erb
<%= render @entry %>

<div class="w-full flex justify-center" >
  <%= link_to "Back to Entries", root_path, class: "btn btn-primary mt-4" %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Foodlog</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/daisyui@4.11.1/dist/full.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.tailwindcss.com"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/header" %>

    <% if notice.present? %>
    <div role="alert" class="alert alert-info">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
      <span>
        <%= notice %>
      </span>
    </div>
    <% end %>

    <% if alert.present? %>
    <div role="alert" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
      <span>Oh snap! 
        <%= alert %>
      </span>
    </div>
    <% end %>

    <main class="container mx-auto my-8 px-4">
    <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="shadow-lg">
    <div class="navbar bg-base-100">
        <div class="container mx-auto">
            <div class="flex-1">
                <%= link_to "FoodLog", entries_path, class: "btn btn-ghost text-2xl" %>
            </div>
            <div class="flex-none">
                <%= link_to new_entry_path do %>
                    <button class="btn btn-active btn-primary">
                        New Entry
                    </button>
                <% end %>
            </div>
        </div>
    </div>
    <div class="container mx-auto flex justify-center w-full">
        <h1 class="text-2xl semibold mb-4">
            <% if content_for(:title) %>
                <%= yield(:title) %>
            <% else %>
                FoodLog Entry
            <% end %>
        </h1>
    </div>
</div>